version: "3.8"

services:
  web:
    container_name: api
    build: .
    ports:
      - "5000:5000"
      - "7070:7070"
    environment:
      - PORT=5000
#    depends_on:
#      - postgesql
    restart: always
    volumes:
      - ./:/app
    networks:
      - web_api

  prometheus:
    container_name: prometheus_container
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=20d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    networks:
      - web_api

  grafana:
    container_name: grafana_container
    restart: always
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      - web_api
networks:
  web_api:
    driver: bridge